/**
 * Hand-written schema types for the Supabase client.
 *
 * Without these the client infers `never` for every table and silently accepts
 * nothing. Written by hand rather than generated so the app has no dependency on
 * the Supabase CLI being installed and linked; keep in sync with
 * supabase/setup.sql and the supabase/migrate-*.sql files.
 */

type Timestamp = string;

type TeamRow = {
  id: string;
  round: number;
  name: string;
  color: string;
  sort_order: number;
  created_at: Timestamp;
};

type PlayerRow = { id: string; name: string; created_at: Timestamp };

type RosterRow = { round: number; player_id: string; team_id: string };

type TaskRow = {
  id: string;
  /** Stable task key used for per-field edits. */
  slug: string;
  round: number;
  title: string;
  /** The planning doc's original wording, kept for provenance. Empty if there was none. */
  doc_title: string;
  points: number;
  scoring_mode: "fixed" | "quantity";
  measurement_label: string;
  points_per_unit: number;
  /** Dormant legacy-data guard; never selected into a task payload. */
  is_secret: boolean;
  active: boolean;
  /** Position within the round in the planning doc; the tie-break inside a tier. */
  doc_order: number;
  /** Generated display order. Never written. */
  sort_order: number;
  // Planning only, never shown to a player.
  prop: string;
  note: string;
  rewrite: boolean;
  created_at: Timestamp;
  updated_at: Timestamp;
};

type SubmissionRow = {
  id: string;
  round: number;
  task_id: string;
  player_id: string;
  team_id: string;
  task_points: number;
  scoring_mode_snapshot: "fixed" | "quantity";
  points_per_unit_snapshot: number;
  measurement_value: number | null;
  object_name: string;
  media_type: string | null;
  size_bytes: number | null;
  status: "uploading" | "pending" | "approved" | "rejected";
  points_awarded: number | null;
  reject_reason: string | null;
  // Several files that make up one piece of evidence. One row is still one file;
  // this is what the judge reviews and decides as a unit. Nullable because rows
  // created before the column exists have none -- read it as `group_id ?? id`.
  group_id: string | null;
  // Player-written, optional: what the judge is looking at.
  note: string | null;
  created_at: Timestamp;
  judged_at: Timestamp | null;
};

type SettingRow = { key: string; value: string | null };

type TeamScoreRow = {
  team_id: string;
  round: number;
  name: string;
  color: string;
  sort_order: number;
  points: number;
  tasks_scored: number;
};

/**
 * Columns with database defaults are optional on insert; `ReadOnly` ones are
 * generated by Postgres and rejected outright if written.
 */
type Table<Row, Optional extends keyof Row, ReadOnly extends keyof Row = never> = {
  Row: Row;
  Insert: Omit<Row, Optional | ReadOnly> & Partial<Pick<Row, Exclude<Optional, ReadOnly>>>;
  Update: Partial<Omit<Row, ReadOnly>>;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      teams: Table<TeamRow, "id" | "sort_order" | "created_at">;
      players: Table<PlayerRow, "id" | "created_at">;
      roster: Table<RosterRow, never>;
      tasks: Table<
        TaskRow,
        | "id"
        | "slug"
        | "doc_title"
        | "scoring_mode"
        | "measurement_label"
        | "points_per_unit"
        | "is_secret"
        | "active"
        | "doc_order"
        | "prop"
        | "note"
        | "rewrite"
        | "created_at"
        | "updated_at",
        "sort_order"
      >;
      submissions: Table<
        SubmissionRow,
        | "id"
        | "media_type"
        | "size_bytes"
        | "measurement_value"
        | "scoring_mode_snapshot"
        | "points_per_unit_snapshot"
        | "status"
        | "points_awarded"
        | "reject_reason"
        | "group_id"
        | "note"
        | "created_at"
        | "judged_at"
      >;
      settings: Table<SettingRow, never>;
    };
    Views: {
      team_scores: { Row: TeamScoreRow; Relationships: [] };
    };
    Functions: {
      transition_event: {
        Args: {
          expected_active_round: number;
          expected_started_round: number;
          expected_submissions_open: boolean;
          next_active_round: number;
          next_started_round: number;
          next_submissions_open: boolean;
        };
        Returns: string;
      };
    };
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
};
