/**
 * Hand-written schema types for the Supabase client.
 *
 * Without these the client infers `never` for every table and silently accepts
 * nothing. Written by hand rather than generated so the app has no dependency on
 * the Supabase CLI being installed and linked; keep in sync with
 * supabase/setup.sql and the supabase/migrate-*.sql files.
 */

type Timestamp = string;

type TeamRow = {
  id: string;
  round: number;
  name: string;
  color: string;
  sort_order: number;
  created_at: Timestamp;
};

type PlayerRow = { id: string; name: string; created_at: Timestamp };

type RosterRow = { round: number; player_id: string; team_id: string };

type TaskRow = {
  id: string;
  /**
   * The task's stable key. A secret challenge is offered in both halves of the
   * event and `round` is 1 or 2, so it is two rows sharing one slug.
   */
  slug: string;
  round: number;
  title: string;
  /** The planning doc's original wording, kept for provenance. Empty if there was none. */
  doc_title: string;
  points: number;
  scoring_mode: "fixed" | "quantity" | "competition";
  measurement_label: string;
  measurement_threshold: number;
  points_per_unit: number;
  measurement_cap: number | null;
  competition_bonus: number;
  requires_video: boolean;
  is_secret: boolean;
  revealed_at: Timestamp | null;
  active: boolean;
  /** Position within the round in the planning doc; the tie-break inside a tier. */
  doc_order: number;
  /** Generated from (is_secret, points, doc_order). Never written. */
  sort_order: number;
  // Planning only, never shown to a player. The canvas owns these; the app reads
  // them nowhere, and they are here so the client does not reject a `select *`.
  difficulty: number;
  guts: number;
  luck: number;
  payoff: number;
  risk: number;
  prop: string;
  note: string;
  rewrite: boolean;
  tier_ok: number | null;
  created_at: Timestamp;
  updated_at: Timestamp;
};

type SubmissionRow = {
  id: string;
  round: number;
  task_id: string;
  player_id: string;
  team_id: string;
  task_points: number;
  scoring_mode_snapshot: "fixed" | "quantity" | "competition";
  measurement_threshold_snapshot: number;
  points_per_unit_snapshot: number;
  measurement_cap_snapshot: number | null;
  competition_bonus_snapshot: number;
  measurement_value: number | null;
  object_name: string;
  media_type: string | null;
  size_bytes: number | null;
  status: "uploading" | "pending" | "approved" | "rejected";
  points_awarded: number | null;
  reject_reason: string | null;
  // Several files that make up one piece of evidence. One row is still one file;
  // this is what the judge reviews and decides as a unit. Nullable because rows
  // created before the column exists have none -- read it as `group_id ?? id`.
  group_id: string | null;
  // Player-written, optional: what the judge is looking at.
  note: string | null;
  created_at: Timestamp;
  judged_at: Timestamp | null;
};

type SettingRow = { key: string; value: string | null };

type TeamScoreRow = {
  team_id: string;
  round: number;
  name: string;
  color: string;
  sort_order: number;
  points: number;
  tasks_scored: number;
};

/**
 * Columns with database defaults are optional on insert; `ReadOnly` ones are
 * generated by Postgres and rejected outright if written.
 */
type Table<Row, Optional extends keyof Row, ReadOnly extends keyof Row = never> = {
  Row: Row;
  Insert: Omit<Row, Optional | ReadOnly> & Partial<Pick<Row, Exclude<Optional, ReadOnly>>>;
  Update: Partial<Omit<Row, ReadOnly>>;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      teams: Table<TeamRow, "id" | "sort_order" | "created_at">;
      players: Table<PlayerRow, "id" | "created_at">;
      roster: Table<RosterRow, never>;
      tasks: Table<
        TaskRow,
        | "id"
        | "slug"
        | "doc_title"
        | "scoring_mode"
        | "measurement_label"
        | "measurement_threshold"
        | "points_per_unit"
        | "measurement_cap"
        | "competition_bonus"
        | "requires_video"
        | "is_secret"
        | "revealed_at"
        | "active"
        | "doc_order"
        | "difficulty"
        | "guts"
        | "luck"
        | "payoff"
        | "risk"
        | "prop"
        | "note"
        | "rewrite"
        | "tier_ok"
        | "created_at"
        | "updated_at",
        "sort_order"
      >;
      submissions: Table<
        SubmissionRow,
        | "id"
        | "media_type"
        | "size_bytes"
        | "measurement_value"
        | "scoring_mode_snapshot"
        | "measurement_threshold_snapshot"
        | "points_per_unit_snapshot"
        | "measurement_cap_snapshot"
        | "competition_bonus_snapshot"
        | "status"
        | "points_awarded"
        | "reject_reason"
        | "group_id"
        | "note"
        | "created_at"
        | "judged_at"
      >;
      settings: Table<SettingRow, never>;
    };
    Views: {
      team_scores: { Row: TeamScoreRow; Relationships: [] };
    };
    Functions: Record<never, never>;
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
};
